Global:
  debug: false
  use_gpu: true
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 5
  save_model_dir: /workspace/PaddleOCR/output/rec/an_rec_r50_1107
  save_epoch_step: 3
  eval_batch_step:
  - 0
  - 2000
  cal_metric_during_train: true
  pretrained_model: /workspace/PaddleOCR/output/yi_r50_srn_1026/best_accuracy
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: null
  character_dict_path: ppocr/utils/en_dict.txt
  character_type: EN
  max_text_length: 25
  num_heads: 8
  infer_mode: false
  use_space_char: false
  save_res_path: /workspace/PaddleOCR/output/rec_csc/predict_an_srn_1109.txt
  distributed: false
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10.0
  lr:
    learning_rate: 0.0001
Architecture:
  model_type: rec
  algorithm: SRN
  in_channels: 1
  Transform: null
  Backbone:
    name: ResNetFPN
  Head:
    name: SRNHead
    max_text_length: 25
    num_heads: 8
    num_encoder_TUs: 2
    num_decoder_TUs: 4
    hidden_dims: 512
Loss:
  name: SRNLoss
PostProcess:
  name: SRNLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /workspace/csc_competition/data/train_crop_bk/
    label_file_list:
    - /workspace/csc_competition/data/train_list.txt
    - /workspace/csc_competition/data/train_fake_1109.txt
    - /workspace/csc_competition/data/train_p.txt
    ratio_list:
    - 0.7
    - 0.2
    - 0.1
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - SRNLabelEncode: null
    - SRNRecResizeImg:
        image_shape:
        - 1
        - 64
        - 256
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
        - encoder_word_pos
        - gsrm_word_pos
        - gsrm_slf_attn_bias1
        - gsrm_slf_attn_bias2
  loader:
    shuffle: true
    batch_size_per_card: 64
    drop_last: false
    num_workers: 4
    use_shared_memory: false
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /workspace/csc_competition/data/valid_db_crop/
    label_file_list:
    - /workspace/csc_competition/data/valid_list_1024.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - SRNLabelEncode: null
    - SRNRecResizeImg:
        image_shape:
        - 1
        - 64
        - 256
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
        - encoder_word_pos
        - gsrm_word_pos
        - gsrm_slf_attn_bias1
        - gsrm_slf_attn_bias2
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 32
    num_workers: 4
    use_shared_memory: false
